# Common application properties
spring:
  application:
    name: my-application
  messages:
    basename: messages
  main:
    allow-bean-definition-overriding: true

# Default server configuration
server:
  error:
    include-message: always

# Default logging configuration
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Default feature flags
feature:
  enable-feature-x: false