spring:
  application:
    name: default-service

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG



#server:
#  port: 8080