spring:
  application:
    name: default-service
  cloud:
    config:
      uri: http://localhost:8888
      failFast: true
      retry:
        maxAttempts: 6
        initialInterval: 2000
      label: main

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8080