spring:
  application:
    name: service-a dev profile
test:
  message: This is a message from service A using the dev profile.

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

