# Development-specific application properties
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:h2:mem:devdb
    driver-class-name: org.h2.Driver
    username: devuser
    password: devpassword
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cache:
    type: none

# Server configuration for development
server:
  port: 8081
  servlet:
    context-path: /dev

# Logging configuration for development
logging:
  level:
    root: DEBUG
    org.springframework: DEBUG

# Development-specific feature flags
feature:
  enable-experimental: true